server:
    port: 8081
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: sa
        url: jdbc:h2:mem:camadabe
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
